var NAVTREEINDEX1 =
{
"sdf_pg.html#sdf_element_clusters":[7,16],
"sdf_pg.html#sdf_element_config_item":[7,4],
"sdf_pg.html#sdf_element_config_items":[7,11],
"sdf_pg.html#sdf_element_dap":[7,9],
"sdf_pg.html#sdf_element_debug":[7,3],
"sdf_pg.html#sdf_element_debug_and_trace_config":[7,2],
"sdf_pg.html#sdf_element_device":[7,10],
"sdf_pg.html#sdf_element_device_info_item":[7,13],
"sdf_pg.html#sdf_element_device_info_items":[7,12],
"sdf_pg.html#sdf_element_platform":[7,7],
"sdf_pg.html#sdf_element_scanchain":[7,8],
"sdf_pg.html#sdf_element_system_description":[7,1],
"sdf_pg.html#sdf_element_topology":[7,14],
"sdf_pg.html#sdf_element_topology_link":[7,15],
"sdf_pg.html#sdf_element_trace":[7,5],
"sdf_pg.html#sdf_element_trace_capture":[7,6],
"sdf_pg.html#sdf_structure":[7,0]
};
