var NAVTREEINDEX1 =
{
"sdf_pg.html#sdf_element_clusters":[8,16],
"sdf_pg.html#sdf_element_config_item":[8,4],
"sdf_pg.html#sdf_element_config_items":[8,11],
"sdf_pg.html#sdf_element_dap":[8,9],
"sdf_pg.html#sdf_element_debug":[8,3],
"sdf_pg.html#sdf_element_debug_and_trace_config":[8,2],
"sdf_pg.html#sdf_element_device":[8,10],
"sdf_pg.html#sdf_element_device_info_item":[8,13],
"sdf_pg.html#sdf_element_device_info_items":[8,12],
"sdf_pg.html#sdf_element_platform":[8,7],
"sdf_pg.html#sdf_element_scanchain":[8,8],
"sdf_pg.html#sdf_element_system_description":[8,1],
"sdf_pg.html#sdf_element_topology":[8,14],
"sdf_pg.html#sdf_element_topology_link":[8,15],
"sdf_pg.html#sdf_element_trace":[8,5],
"sdf_pg.html#sdf_element_trace_capture":[8,6],
"sdf_pg.html#sdf_structure":[8,0]
};
